### PR TITLE
bluemix command

### PR DESCRIPTION
**Pull request by hacksparrow**
### Description

Added `bluemix` command

#### Related issues

- None

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by bajtos** [comment]
@hacksparrow as a temporary fix making it easier for people to install bluemix-enabled CLI, have you considered changing the generator-loopback dependency to install from a github branch? Something along the following lines:

```
"generator-loopback": "strongloop/generator-loopback#command/bluemix`
```

That way people can try the upcoming CLI version via `npm install -g strongloop/loopback-
cli#command/bluemix`, without having to undertake `npm link` pain.

(A similar change would be requires in generator-loopback to install loopback-workspace from a github branch.)

**Comment by hacksparrow** [comment]
@bajtos added the tests. Travis doesn't seem to be using the latest updates, though.

**Comment by raymondfeng** [comment]
@hacksparrow Can you also update https://github.com/strongloop/loopback-cli/blob/master/test/fixtures/help-lb-datasource.txt with `--bluemix` too?

**Comment by hacksparrow** [comment]
@raymondfeng done

**Pull request merged**
