### PR TITLE
support for lb soap command

### PR DESCRIPTION
**Pull request by rashmihunt**
@raymondfeng PTAL

### CODE REVIEW

**Comment by bajtos** [comment]
@rashmihunt also please add your new commands to the file testing help messages - see https://github.com/strongloop/loopback-cli/blob/3e107b099f8ea4ec9a3c539d30d8724a4d269c81/test/help.test.js#L15-L27

**Comment by rashmihunt** [comment]
@slnode test please

**Comment by rashmihunt** [comment]
@bajtos Implemented review comment. Interestingly,  CI is still failing. When I run 'npm test' locally, it's passing 100%.  

As a side note, 'generator-loopback' PR which supports this underlying 'lb soap' feature is still in review https://github.com/strongloop/generator-loopback/pull/262. CI is also failing for this PR because it depends on this loopback-cli PR support.  Kind of a check and an egg problem.

**Comment by bajtos** [comment]
> My recommendation is to wait until strongloop/generator-loopback#262 is landed, then trigger a new CI build of this pull request and wait for the CI to finish in green.

To fix Travis builds, we will need strongloop/generator-loopback#262 to be published to npmjs.org.

**Comment by rashmihunt** [comment]
@slnode test please

**Comment by rashmihunt** [comment]
@slnode test please

**Comment by rashmihunt** [comment]
@slnode test please

**Comment by rashmihunt** [comment]
@slnode test please

**Comment by rashmihunt** [comment]
@bajtos Can we release 2.1.0 version to npm which will have 'lb soap' feature?

**Pull request merged**
